---
- name: "Build container with ansible"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop mina
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm mina
    ignore_errors: yes
  
  - name: remove used image
    command: docker rmi newimage
    ignore_errors: yes
